### ISSUE TITLE
Why the test code saved image is all black?

### ISSUE THREAD

**Issue by 201814476285951** [Edwardlzy/SRCNN#5]

**Comment by Nightree** [comment]
The model's path is error. Modify ./checkpoint/  to  ./checkpoint/srcnn_21/
You can just debug the code and find the problem.

**Comment by 15732031137** [comment]
Hello! First of all, thank you for sharing your ideas here. I recently encountered a problem when I reproduced this program. Can you help me?
  

Traceback (most recent call last):
  File "net.py", line 162, in <module>
    train_SRCNN(images)
  File "net.py", line 92, in train_SRCNN
    train_data, train_label = load_data(train_path)
  File "net.py", line 24, in load_data
    with h5py.File(path, 'r') as hf:
  File "/root/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/root/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './checkpoint/train.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Thank you very much! Looking forward to your reply!
